example.property: "I AM A PROD PROPERTY OVERRIDE"
spring.datasource.url: "jdbc:h2:mem:mydb"
spring.datasource.driverClassName: "org.h2.Driver"
spring.datasource.username: "sa"
spring.datasource.password: "ss"
spring.jpa.hibernate.ddl-auto: "create-drop"
spring.h2.console.enabled: "true"
spring.h2.console.path: "/h2-console"
debug: "true"