server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/suyashs52/book-cloud-config
          searchPaths: /tree/master/src/main/resources/config/licensingservice
          username: hello
          password: hello