server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/Users/suyashsingh01/Downloads/booksconfig/src/main/resources/config/licensingservice